# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b61302e8530d569072f095fe72b1e8e787dd30127b13b94c6bc25e7075696a0ca3b9494d813ba585555f2784fad2bbf808457f0e2ec1314386c4809a847f966

test:
  secret_key_base: 6542c9ddccda70d3e58f2b544ae8e37d5b44d032a15b6eda754541525442e67cc7c442cc09f837bbe9fa66cffc260974c0f2feca969911b760782dde6eeb63c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
